//-------------------------------
// File generated by generate_can_code.py on: 2025-03-11 14:36:24
//-------------------------------

#ifndef INC_CAN_MESSAGES_H_
#define INC_CAN_MESSAGES_H_

#include "can_db.h"

#ifdef __GNUC__
#define PACKED __attribute__((packed))
#else
#define PACKED
#endif

#define CAN_DB_VCU_STATUS_ID 256
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t VEHICLE_STATE : 2;
        uint64_t TORQUE_PLAUSIBLE : 1;
        uint64_t PEDALS_PLAUSIBLE : 1;
        uint64_t TORQUE_DERATING : 1;
        uint64_t VCU_EEPROM_STATE : 2;
        uint64_t CAN_PLAUSIBLE : 1;
        uint64_t APPS_1_PLAUSIBLE : 1;
        uint64_t APPS_1_CONFIG_PLAUSIBLE : 1;
        uint64_t APPS_2_PLAUSIBLE : 1;
        uint64_t APPS_2_CONFIG_PLAUSIBLE : 1;
        uint64_t BSE_F_PLAUSIBLE : 1;
        uint64_t BSE_F_CONFIG_PLAUSIBLE : 1;
        uint64_t BSE_R_PLAUSIBLE : 1;
        uint64_t BSE_R_CONFIG_PLAUSIBLE : 1;
        uint64_t AMK_RL_VALID : 1;
        uint64_t AMK_RR_VALID : 1;
        uint64_t AMK_FL_VALID : 1;
        uint64_t AMK_FR_VALID : 1;
        uint64_t GPS_VALID : 1;
        uint64_t _reserved21 : 3;
        uint64_t GLV_BATTERY_VOLTAGE : 8;
    } fields;
} CANMessage_VCU_STATUS;

#define CAN_DB_VCU_SENSOR_INPUT_ID 1536
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t APPS_1_PERCENT : 12;
        uint64_t APPS_2_PERCENT : 12;
        uint64_t BSE_FRONT_PERCENT : 12;
        uint64_t BSE_REAR_PERCENT : 12;
        uint64_t STEERING_ANGLE : 16;
    } fields;
} CANMessage_VCU_SENSOR_INPUT;

#define CAN_DB_VCU_DEBUG_MESSAGE_ID 1617
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t VCU_DEBUG_0 : 16;
        uint64_t VCU_DEBUG_1 : 16;
        uint64_t VCU_DEBUG_2 : 16;
        uint64_t VCU_DEBUG_3 : 16;
    } fields;
} CANMessage_VCU_DEBUG_MESSAGE;

#define CAN_DB_AMK_RL_ERRORS_1_ID 1284
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t RL_DIAGNOSTIC_NUMBER : 32;
        uint64_t RL_ERROR_INFO_1 : 32;
    } fields;
} CANMessage_AMK_RL_ERRORS_1;

#define CAN_DB_AMK_RL_ERRORS_2_ID 1288
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t RL_ERROR_INFO_2 : 32;
        uint64_t RL_ERROR_INFO_3 : 32;
    } fields;
} CANMessage_AMK_RL_ERRORS_2;

#define CAN_DB_AMK_RL_MOTOR_REQUEST_ID 512
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 8;
        uint64_t RL_INVERTER_ENABLE : 1;
        uint64_t RL_DC_ENABLE : 1;
        uint64_t RL_DRIVER_ENABLE : 1;
        uint64_t RL_ERROR_RESET : 1;
        uint64_t _reserved12 : 4;
        uint64_t RL_TORQUE_SETPOINT : 16;
        uint64_t RL_POSITIVE_TORQUE_LIMIT : 16;
        uint64_t RL_NEGATIVE_TORQUE_LIMIT : 16;
    } fields;
} CANMessage_AMK_RL_MOTOR_REQUEST;

#define CAN_DB_AMK_RL_MOTOR_FEEDBACK_ID 516
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 8;
        uint64_t RL_SYSTEM_READY : 1;
        uint64_t RL_ERROR : 1;
        uint64_t RL_WARNING : 1;
        uint64_t RL_QUIT_DC_ON : 1;
        uint64_t RL_DC_ON : 1;
        uint64_t RL_QUIT_INVERTER : 1;
        uint64_t RL_INVERTER_ON : 1;
        uint64_t RL_DERATING : 1;
        uint64_t RL_ACTUAL_TORQUE_VALUE : 16;
        uint64_t RL_ACTUAL_SPEED_VALUE : 32;
    } fields;
} CANMessage_AMK_RL_MOTOR_FEEDBACK;

#define CAN_DB_AMK_RL_POWER_CONSUMPTION_ID 520
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t RL_DC_BUS_VOLTAGE : 16;
        uint64_t RL_TORQUE_CURRENT_FEEDBACK : 16;
        uint64_t RL_ACTUAL_POWER_VALUE : 32;
    } fields;
} CANMessage_AMK_RL_POWER_CONSUMPTION;

#define CAN_DB_AMK_RL_TEMPERATURES_ID 1280
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t RL_TEMPERATURE_INTERNAL : 16;
        uint64_t RL_TEMPERATURE_EXTERNAL : 16;
        uint64_t RL_TEMPERATURE_SENSOR_MOTOR : 16;
        uint64_t RL_IGBT_TEMPERATURE : 16;
    } fields;
} CANMessage_AMK_RL_TEMPERATURES;

#define CAN_DB_ECUMASTER_GPS_POSITION_ID 1024
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 7;
        uint64_t LATITUDE : 32;
        uint64_t LONGITUDE : 32;
    } fields;
} CANMessage_ECUMASTER_GPS_POSITION;

#define CAN_DB_ECUMASTER_GPS_VELOCITY_ID 1025
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 7;
        uint64_t SPEED : 16;
        uint64_t HEIGHT : 16;
        uint64_t _reserved39 : 8;
        uint64_t SATELLITES_NUMBER : 8;
        uint64_t GPS_FRAME_INDEX : 4;
        uint64_t EMPTY_FRAME_INDEX : 4;
        uint64_t GPS_STATUS : 3;
        uint64_t _reserved61 : 3;
    } fields;
} CANMessage_ECUMASTER_GPS_VELOCITY;

#define CAN_DB_ECUMASTER_GPS_HEADING_IMU0_ID 1026
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 7;
        uint64_t HEADING_MOTION : 16;
        uint64_t HEADING_VEHICLE : 16;
        uint64_t X_ANGLE_RATE : 16;
        uint64_t Y_ANGLE_RATE : 16;
    } fields;
} CANMessage_ECUMASTER_GPS_HEADING_IMU0;

#define CAN_DB_ECUMASTER_GPS_IMU1_ID 1027
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 7;
        uint64_t Z_ANGLE_RATE : 16;
        uint64_t X_ACCELERATION : 16;
        uint64_t Y_ACCELERATION : 16;
        uint64_t Z_ACCELERATION : 16;
    } fields;
} CANMessage_ECUMASTER_GPS_IMU1;

#define CAN_DB_ECUMASTER_GPS_UTC_ID 1028
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t _reserved0 : 7;
        uint64_t UTC_YEAR : 8;
        uint64_t UTC_MONTH : 8;
        uint64_t UTC_DAY : 8;
        uint64_t UTC_HOUR : 8;
        uint64_t UTC_MINUTE : 8;
        uint64_t UTC_SECOND : 8;
        uint64_t UTC_MILLISECOND : 16;
    } fields;
} CANMessage_ECUMASTER_GPS_UTC;

#define CAN_DB_BMS_CELL_VOLTAGES_0_7_ID 1792
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_0 : 8;
        uint64_t CELL_VOLTAGE_1 : 8;
        uint64_t CELL_VOLTAGE_2 : 8;
        uint64_t CELL_VOLTAGE_3 : 8;
        uint64_t CELL_VOLTAGE_4 : 8;
        uint64_t CELL_VOLTAGE_5 : 8;
        uint64_t CELL_VOLTAGE_6 : 8;
        uint64_t CELL_VOLTAGE_7 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_0_7;

#define CAN_DB_BMS_CELL_VOLTAGES_8_15_ID 1793
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_8 : 8;
        uint64_t CELL_VOLTAGE_9 : 8;
        uint64_t CELL_VOLTAGE_10 : 8;
        uint64_t CELL_VOLTAGE_11 : 8;
        uint64_t CELL_VOLTAGE_12 : 8;
        uint64_t CELL_VOLTAGE_13 : 8;
        uint64_t CELL_VOLTAGE_14 : 8;
        uint64_t CELL_VOLTAGE_15 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_8_15;

#define CAN_DB_BMS_CELL_VOLTAGES_16_23_ID 1794
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_16 : 8;
        uint64_t CELL_VOLTAGE_17 : 8;
        uint64_t CELL_VOLTAGE_18 : 8;
        uint64_t CELL_VOLTAGE_19 : 8;
        uint64_t CELL_VOLTAGE_20 : 8;
        uint64_t CELL_VOLTAGE_21 : 8;
        uint64_t CELL_VOLTAGE_22 : 8;
        uint64_t CELL_VOLTAGE_23 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_16_23;

#define CAN_DB_BMS_CELL_VOLTAGES_24_31_ID 1795
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_24 : 8;
        uint64_t CELL_VOLTAGE_25 : 8;
        uint64_t CELL_VOLTAGE_26 : 8;
        uint64_t CELL_VOLTAGE_27 : 8;
        uint64_t CELL_VOLTAGE_28 : 8;
        uint64_t CELL_VOLTAGE_29 : 8;
        uint64_t CELL_VOLTAGE_30 : 8;
        uint64_t CELL_VOLTAGE_31 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_24_31;

#define CAN_DB_BMS_CELL_VOLTAGES_32_39_ID 1796
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_32 : 8;
        uint64_t CELL_VOLTAGE_33 : 8;
        uint64_t CELL_VOLTAGE_34 : 8;
        uint64_t CELL_VOLTAGE_35 : 8;
        uint64_t CELL_VOLTAGE_36 : 8;
        uint64_t CELL_VOLTAGE_37 : 8;
        uint64_t CELL_VOLTAGE_38 : 8;
        uint64_t CELL_VOLTAGE_39 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_32_39;

#define CAN_DB_BMS_CELL_VOLTAGES_40_47_ID 1797
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_40 : 8;
        uint64_t CELL_VOLTAGE_41 : 8;
        uint64_t CELL_VOLTAGE_42 : 8;
        uint64_t CELL_VOLTAGE_43 : 8;
        uint64_t CELL_VOLTAGE_44 : 8;
        uint64_t CELL_VOLTAGE_45 : 8;
        uint64_t CELL_VOLTAGE_46 : 8;
        uint64_t CELL_VOLTAGE_47 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_40_47;

#define CAN_DB_BMS_CELL_VOLTAGES_48_55_ID 1798
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_48 : 8;
        uint64_t CELL_VOLTAGE_49 : 8;
        uint64_t CELL_VOLTAGE_50 : 8;
        uint64_t CELL_VOLTAGE_51 : 8;
        uint64_t CELL_VOLTAGE_52 : 8;
        uint64_t CELL_VOLTAGE_53 : 8;
        uint64_t CELL_VOLTAGE_54 : 8;
        uint64_t CELL_VOLTAGE_55 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_48_55;

#define CAN_DB_BMS_CELL_VOLTAGES_56_63_ID 1799
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_56 : 8;
        uint64_t CELL_VOLTAGE_57 : 8;
        uint64_t CELL_VOLTAGE_58 : 8;
        uint64_t CELL_VOLTAGE_59 : 8;
        uint64_t CELL_VOLTAGE_60 : 8;
        uint64_t CELL_VOLTAGE_61 : 8;
        uint64_t CELL_VOLTAGE_62 : 8;
        uint64_t CELL_VOLTAGE_63 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_56_63;

#define CAN_DB_BMS_CELL_VOLTAGES_64_71_ID 1800
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_64 : 8;
        uint64_t CELL_VOLTAGE_65 : 8;
        uint64_t CELL_VOLTAGE_66 : 8;
        uint64_t CELL_VOLTAGE_67 : 8;
        uint64_t CELL_VOLTAGE_68 : 8;
        uint64_t CELL_VOLTAGE_69 : 8;
        uint64_t CELL_VOLTAGE_70 : 8;
        uint64_t CELL_VOLTAGE_71 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_64_71;

#define CAN_DB_BMS_CELL_VOLTAGES_72_79_ID 1801
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_72 : 8;
        uint64_t CELL_VOLTAGE_73 : 8;
        uint64_t CELL_VOLTAGE_74 : 8;
        uint64_t CELL_VOLTAGE_75 : 8;
        uint64_t CELL_VOLTAGE_76 : 8;
        uint64_t CELL_VOLTAGE_77 : 8;
        uint64_t CELL_VOLTAGE_78 : 8;
        uint64_t CELL_VOLTAGE_79 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_72_79;

#define CAN_DB_BMS_CELL_VOLTAGES_80_87_ID 1802
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_80 : 8;
        uint64_t CELL_VOLTAGE_81 : 8;
        uint64_t CELL_VOLTAGE_82 : 8;
        uint64_t CELL_VOLTAGE_83 : 8;
        uint64_t CELL_VOLTAGE_84 : 8;
        uint64_t CELL_VOLTAGE_85 : 8;
        uint64_t CELL_VOLTAGE_86 : 8;
        uint64_t CELL_VOLTAGE_87 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_80_87;

#define CAN_DB_BMS_CELL_VOLTAGES_88_95_ID 1803
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_88 : 8;
        uint64_t CELL_VOLTAGE_89 : 8;
        uint64_t CELL_VOLTAGE_90 : 8;
        uint64_t CELL_VOLTAGE_91 : 8;
        uint64_t CELL_VOLTAGE_92 : 8;
        uint64_t CELL_VOLTAGE_93 : 8;
        uint64_t CELL_VOLTAGE_94 : 8;
        uint64_t CELL_VOLTAGE_95 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_88_95;

#define CAN_DB_BMS_CELL_VOLTAGES_96_103_ID 1804
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_96 : 8;
        uint64_t CELL_VOLTAGE_97 : 8;
        uint64_t CELL_VOLTAGE_98 : 8;
        uint64_t CELL_VOLTAGE_99 : 8;
        uint64_t CELL_VOLTAGE_100 : 8;
        uint64_t CELL_VOLTAGE_101 : 8;
        uint64_t CELL_VOLTAGE_102 : 8;
        uint64_t CELL_VOLTAGE_103 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_96_103;

#define CAN_DB_BMS_CELL_VOLTAGES_104_111_ID 1805
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_104 : 8;
        uint64_t CELL_VOLTAGE_105 : 8;
        uint64_t CELL_VOLTAGE_106 : 8;
        uint64_t CELL_VOLTAGE_107 : 8;
        uint64_t CELL_VOLTAGE_108 : 8;
        uint64_t CELL_VOLTAGE_109 : 8;
        uint64_t CELL_VOLTAGE_110 : 8;
        uint64_t CELL_VOLTAGE_111 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_104_111;

#define CAN_DB_BMS_CELL_VOLTAGES_112_119_ID 1806
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t CELL_VOLTAGE_112 : 8;
        uint64_t CELL_VOLTAGE_113 : 8;
        uint64_t CELL_VOLTAGE_114 : 8;
        uint64_t CELL_VOLTAGE_115 : 8;
        uint64_t CELL_VOLTAGE_116 : 8;
        uint64_t CELL_VOLTAGE_117 : 8;
        uint64_t CELL_VOLTAGE_118 : 8;
        uint64_t CELL_VOLTAGE_119 : 8;
    } fields;
} CANMessage_BMS_CELL_VOLTAGES_112_119;

#define CAN_DB_BMS_TEMPERATURES_0_7_ID 1808
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t TEMPERATURE_0 : 8;
        uint64_t TEMPERATURE_1 : 8;
        uint64_t TEMPERATURE_2 : 8;
        uint64_t TEMPERATURE_3 : 8;
        uint64_t TEMPERATURE_4 : 8;
        uint64_t TEMPERATURE_5 : 8;
        uint64_t TEMPERATURE_6 : 8;
        uint64_t TEMPERATURE_7 : 8;
    } fields;
} CANMessage_BMS_TEMPERATURES_0_7;

#define CAN_DB_BMS_TEMPERATURES_8_15_ID 1809
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t TEMPERATURE_8 : 8;
        uint64_t TEMPERATURE_9 : 8;
        uint64_t TEMPERATURE_10 : 8;
        uint64_t TEMPERATURE_11 : 8;
        uint64_t TEMPERATURE_12 : 8;
        uint64_t TEMPERATURE_13 : 8;
        uint64_t TEMPERATURE_14 : 8;
        uint64_t TEMPERATURE_15 : 8;
    } fields;
} CANMessage_BMS_TEMPERATURES_8_15;

#define CAN_DB_BMS_TEMPERATURES_16_31_ID 1810
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t TEMPERATURE_16 : 8;
        uint64_t TEMPERATURE_17 : 8;
        uint64_t TEMPERATURE_18 : 8;
        uint64_t TEMPERATURE_19 : 8;
        uint64_t TEMPERATURE_20 : 8;
        uint64_t TEMPERATURE_21 : 8;
        uint64_t TEMPERATURE_22 : 8;
        uint64_t TEMPERATURE_23 : 8;
    } fields;
} CANMessage_BMS_TEMPERATURES_16_31;

#define CAN_DB_BMS_TEMPERATURES_32_39_ID 1811
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t TEMPERATURE_32 : 8;
        uint64_t TEMPERATURE_33 : 8;
        uint64_t TEMPERATURE_34 : 8;
        uint64_t TEMPERATURE_35 : 8;
        uint64_t TEMPERATURE_36 : 8;
        uint64_t TEMPERATURE_37 : 8;
        uint64_t TEMPERATURE_38 : 8;
        uint64_t TEMPERATURE_39 : 8;
    } fields;
} CANMessage_BMS_TEMPERATURES_32_39;

#define CAN_DB_BMS_TEMPERATURES_40_47_ID 1812
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t TEMPERATURE_40 : 8;
        uint64_t TEMPERATURE_41 : 8;
        uint64_t TEMPERATURE_42 : 8;
        uint64_t TEMPERATURE_43 : 8;
        uint64_t TEMPERATURE_44 : 8;
        uint64_t TEMPERATURE_45 : 8;
        uint64_t TEMPERATURE_46 : 8;
        uint64_t TEMPERATURE_47 : 8;
    } fields;
} CANMessage_BMS_TEMPERATURES_40_47;

#define CAN_DB_BMS_TEMPERATURES_48_49_ID 1813
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t TEMPERATURE_48 : 8;
        uint64_t TEMPERATURE_49 : 8;
        uint64_t _reserved16 : 48;
    } fields;
} CANMessage_BMS_TEMPERATURES_48_49;

#define CAN_DB_VCU_EEPROM_COMMAND_ID 1872
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t VCU_EEPROM_COMMAND_INSTRUCTION : 16;
        uint64_t VCU_EEPROM_COMMAND_ADDRESS : 16;
        uint64_t VCU_EEPROM_COMMAND_DATA : 32;
    } fields;
} CANMessage_VCU_EEPROM_COMMAND;

#define CAN_DB_VCU_EEPROM_RESPONSE_ID 1873
typedef union {
    uint64_t as_u64;
    struct PACKED {
        uint64_t VCU_EEPROM_COMMAND_INSTRUCTION : 16;
        uint64_t VCU_EEPROM_COMMAND_ADDRESS : 16;
        uint64_t VCU_EEPROM_COMMAND_DATA : 32;
    } fields;
} CANMessage_VCU_EEPROM_RESPONSE;

#define CAN_DB_VCU_STATUS_SIGNAL_COUNT 20
static const CANDatabaseSignal_t can_db_signals_VCU_STATUS[CAN_DB_VCU_STATUS_SIGNAL_COUNT] = {
    {.name = "VEHICLE_STATE", .bitpos = 0, .bitmask = 0x3ULL},
    {.name = "TORQUE_PLAUSIBLE", .bitpos = 2, .bitmask = 0x1ULL},
    {.name = "PEDALS_PLAUSIBLE", .bitpos = 3, .bitmask = 0x1ULL},
    {.name = "TORQUE_DERATING", .bitpos = 4, .bitmask = 0x1ULL},
    {.name = "VCU_EEPROM_STATE", .bitpos = 5, .bitmask = 0x3ULL},
    {.name = "CAN_PLAUSIBLE", .bitpos = 7, .bitmask = 0x1ULL},
    {.name = "APPS_1_PLAUSIBLE", .bitpos = 8, .bitmask = 0x1ULL},
    {.name = "APPS_1_CONFIG_PLAUSIBLE", .bitpos = 9, .bitmask = 0x1ULL},
    {.name = "APPS_2_PLAUSIBLE", .bitpos = 10, .bitmask = 0x1ULL},
    {.name = "APPS_2_CONFIG_PLAUSIBLE", .bitpos = 11, .bitmask = 0x1ULL},
    {.name = "BSE_F_PLAUSIBLE", .bitpos = 12, .bitmask = 0x1ULL},
    {.name = "BSE_F_CONFIG_PLAUSIBLE", .bitpos = 13, .bitmask = 0x1ULL},
    {.name = "BSE_R_PLAUSIBLE", .bitpos = 14, .bitmask = 0x1ULL},
    {.name = "BSE_R_CONFIG_PLAUSIBLE", .bitpos = 15, .bitmask = 0x1ULL},
    {.name = "AMK_RL_VALID", .bitpos = 16, .bitmask = 0x1ULL},
    {.name = "AMK_RR_VALID", .bitpos = 17, .bitmask = 0x1ULL},
    {.name = "AMK_FL_VALID", .bitpos = 18, .bitmask = 0x1ULL},
    {.name = "AMK_FR_VALID", .bitpos = 19, .bitmask = 0x1ULL},
    {.name = "GPS_VALID", .bitpos = 20, .bitmask = 0x1ULL},
    {.name = "GLV_BATTERY_VOLTAGE", .bitpos = 24, .bitmask = 0xFFULL},
};

#define CAN_DB_VCU_SENSOR_INPUT_SIGNAL_COUNT 5
static const CANDatabaseSignal_t can_db_signals_VCU_SENSOR_INPUT[CAN_DB_VCU_SENSOR_INPUT_SIGNAL_COUNT] = {
    {.name = "APPS_1_PERCENT", .bitpos = 0, .bitmask = 0xFFFULL},
    {.name = "APPS_2_PERCENT", .bitpos = 12, .bitmask = 0xFFFULL},
    {.name = "BSE_FRONT_PERCENT", .bitpos = 24, .bitmask = 0xFFFULL},
    {.name = "BSE_REAR_PERCENT", .bitpos = 36, .bitmask = 0xFFFULL},
    {.name = "STEERING_ANGLE", .bitpos = 48, .bitmask = 0xFFFFULL},
};

#define CAN_DB_VCU_DEBUG_MESSAGE_SIGNAL_COUNT 4
static const CANDatabaseSignal_t can_db_signals_VCU_DEBUG_MESSAGE[CAN_DB_VCU_DEBUG_MESSAGE_SIGNAL_COUNT] = {
    {.name = "VCU_DEBUG_0", .bitpos = 0, .bitmask = 0xFFFFULL},
    {.name = "VCU_DEBUG_1", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "VCU_DEBUG_2", .bitpos = 32, .bitmask = 0xFFFFULL},
    {.name = "VCU_DEBUG_3", .bitpos = 48, .bitmask = 0xFFFFULL},
};

#define CAN_DB_AMK_RL_ERRORS_1_SIGNAL_COUNT 2
static const CANDatabaseSignal_t can_db_signals_AMK_RL_ERRORS_1[CAN_DB_AMK_RL_ERRORS_1_SIGNAL_COUNT] = {
    {.name = "RL_DIAGNOSTIC_NUMBER", .bitpos = 0, .bitmask = 0xFFFFFFFFULL},
    {.name = "RL_ERROR_INFO_1", .bitpos = 32, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_AMK_RL_ERRORS_2_SIGNAL_COUNT 2
static const CANDatabaseSignal_t can_db_signals_AMK_RL_ERRORS_2[CAN_DB_AMK_RL_ERRORS_2_SIGNAL_COUNT] = {
    {.name = "RL_ERROR_INFO_2", .bitpos = 0, .bitmask = 0xFFFFFFFFULL},
    {.name = "RL_ERROR_INFO_3", .bitpos = 32, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_AMK_RL_MOTOR_REQUEST_SIGNAL_COUNT 7
static const CANDatabaseSignal_t can_db_signals_AMK_RL_MOTOR_REQUEST[CAN_DB_AMK_RL_MOTOR_REQUEST_SIGNAL_COUNT] = {
    {.name = "RL_INVERTER_ENABLE", .bitpos = 8, .bitmask = 0x1ULL},
    {.name = "RL_DC_ENABLE", .bitpos = 9, .bitmask = 0x1ULL},
    {.name = "RL_DRIVER_ENABLE", .bitpos = 10, .bitmask = 0x1ULL},
    {.name = "RL_ERROR_RESET", .bitpos = 11, .bitmask = 0x1ULL},
    {.name = "RL_TORQUE_SETPOINT", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "RL_POSITIVE_TORQUE_LIMIT", .bitpos = 32, .bitmask = 0xFFFFULL},
    {.name = "RL_NEGATIVE_TORQUE_LIMIT", .bitpos = 48, .bitmask = 0xFFFFULL},
};

#define CAN_DB_AMK_RL_MOTOR_FEEDBACK_SIGNAL_COUNT 10
static const CANDatabaseSignal_t can_db_signals_AMK_RL_MOTOR_FEEDBACK[CAN_DB_AMK_RL_MOTOR_FEEDBACK_SIGNAL_COUNT] = {
    {.name = "RL_SYSTEM_READY", .bitpos = 8, .bitmask = 0x1ULL},
    {.name = "RL_ERROR", .bitpos = 9, .bitmask = 0x1ULL},
    {.name = "RL_WARNING", .bitpos = 10, .bitmask = 0x1ULL},
    {.name = "RL_QUIT_DC_ON", .bitpos = 11, .bitmask = 0x1ULL},
    {.name = "RL_DC_ON", .bitpos = 12, .bitmask = 0x1ULL},
    {.name = "RL_QUIT_INVERTER", .bitpos = 13, .bitmask = 0x1ULL},
    {.name = "RL_INVERTER_ON", .bitpos = 14, .bitmask = 0x1ULL},
    {.name = "RL_DERATING", .bitpos = 15, .bitmask = 0x1ULL},
    {.name = "RL_ACTUAL_TORQUE_VALUE", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "RL_ACTUAL_SPEED_VALUE", .bitpos = 32, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_AMK_RL_POWER_CONSUMPTION_SIGNAL_COUNT 3
static const CANDatabaseSignal_t can_db_signals_AMK_RL_POWER_CONSUMPTION[CAN_DB_AMK_RL_POWER_CONSUMPTION_SIGNAL_COUNT] = {
    {.name = "RL_DC_BUS_VOLTAGE", .bitpos = 0, .bitmask = 0xFFFFULL},
    {.name = "RL_TORQUE_CURRENT_FEEDBACK", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "RL_ACTUAL_POWER_VALUE", .bitpos = 32, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_AMK_RL_TEMPERATURES_SIGNAL_COUNT 4
static const CANDatabaseSignal_t can_db_signals_AMK_RL_TEMPERATURES[CAN_DB_AMK_RL_TEMPERATURES_SIGNAL_COUNT] = {
    {.name = "RL_TEMPERATURE_INTERNAL", .bitpos = 0, .bitmask = 0xFFFFULL},
    {.name = "RL_TEMPERATURE_EXTERNAL", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "RL_TEMPERATURE_SENSOR_MOTOR", .bitpos = 32, .bitmask = 0xFFFFULL},
    {.name = "RL_IGBT_TEMPERATURE", .bitpos = 48, .bitmask = 0xFFFFULL},
};

#define CAN_DB_ECUMASTER_GPS_POSITION_SIGNAL_COUNT 2
static const CANDatabaseSignal_t can_db_signals_ECUMASTER_GPS_POSITION[CAN_DB_ECUMASTER_GPS_POSITION_SIGNAL_COUNT] = {
    {.name = "LATITUDE", .bitpos = 7, .bitmask = 0xFFFFFFFFULL},
    {.name = "LONGITUDE", .bitpos = 39, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_ECUMASTER_GPS_VELOCITY_SIGNAL_COUNT 6
static const CANDatabaseSignal_t can_db_signals_ECUMASTER_GPS_VELOCITY[CAN_DB_ECUMASTER_GPS_VELOCITY_SIGNAL_COUNT] = {
    {.name = "SPEED", .bitpos = 7, .bitmask = 0xFFFFULL},
    {.name = "HEIGHT", .bitpos = 23, .bitmask = 0xFFFFULL},
    {.name = "SATELLITES_NUMBER", .bitpos = 47, .bitmask = 0xFFULL},
    {.name = "GPS_FRAME_INDEX", .bitpos = 51, .bitmask = 0xFULL},
    {.name = "EMPTY_FRAME_INDEX", .bitpos = 55, .bitmask = 0xFULL},
    {.name = "GPS_STATUS", .bitpos = 58, .bitmask = 0x7ULL},
};

#define CAN_DB_ECUMASTER_GPS_HEADING_IMU0_SIGNAL_COUNT 4
static const CANDatabaseSignal_t can_db_signals_ECUMASTER_GPS_HEADING_IMU0[CAN_DB_ECUMASTER_GPS_HEADING_IMU0_SIGNAL_COUNT] = {
    {.name = "HEADING_MOTION", .bitpos = 7, .bitmask = 0xFFFFULL},
    {.name = "HEADING_VEHICLE", .bitpos = 23, .bitmask = 0xFFFFULL},
    {.name = "X_ANGLE_RATE", .bitpos = 39, .bitmask = 0xFFFFULL},
    {.name = "Y_ANGLE_RATE", .bitpos = 55, .bitmask = 0xFFFFULL},
};

#define CAN_DB_ECUMASTER_GPS_IMU1_SIGNAL_COUNT 4
static const CANDatabaseSignal_t can_db_signals_ECUMASTER_GPS_IMU1[CAN_DB_ECUMASTER_GPS_IMU1_SIGNAL_COUNT] = {
    {.name = "Z_ANGLE_RATE", .bitpos = 7, .bitmask = 0xFFFFULL},
    {.name = "X_ACCELERATION", .bitpos = 23, .bitmask = 0xFFFFULL},
    {.name = "Y_ACCELERATION", .bitpos = 39, .bitmask = 0xFFFFULL},
    {.name = "Z_ACCELERATION", .bitpos = 55, .bitmask = 0xFFFFULL},
};

#define CAN_DB_ECUMASTER_GPS_UTC_SIGNAL_COUNT 7
static const CANDatabaseSignal_t can_db_signals_ECUMASTER_GPS_UTC[CAN_DB_ECUMASTER_GPS_UTC_SIGNAL_COUNT] = {
    {.name = "UTC_YEAR", .bitpos = 7, .bitmask = 0xFFULL},
    {.name = "UTC_MONTH", .bitpos = 15, .bitmask = 0xFFULL},
    {.name = "UTC_DAY", .bitpos = 23, .bitmask = 0xFFULL},
    {.name = "UTC_HOUR", .bitpos = 31, .bitmask = 0xFFULL},
    {.name = "UTC_MINUTE", .bitpos = 39, .bitmask = 0xFFULL},
    {.name = "UTC_SECOND", .bitpos = 47, .bitmask = 0xFFULL},
    {.name = "UTC_MILLISECOND", .bitpos = 55, .bitmask = 0xFFFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_0_7_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_0_7[CAN_DB_BMS_CELL_VOLTAGES_0_7_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_0", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_1", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_2", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_3", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_4", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_5", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_6", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_7", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_8_15_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_8_15[CAN_DB_BMS_CELL_VOLTAGES_8_15_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_8", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_9", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_10", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_11", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_12", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_13", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_14", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_15", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_16_23_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_16_23[CAN_DB_BMS_CELL_VOLTAGES_16_23_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_16", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_17", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_18", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_19", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_20", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_21", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_22", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_23", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_24_31_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_24_31[CAN_DB_BMS_CELL_VOLTAGES_24_31_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_24", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_25", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_26", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_27", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_28", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_29", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_30", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_31", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_32_39_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_32_39[CAN_DB_BMS_CELL_VOLTAGES_32_39_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_32", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_33", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_34", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_35", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_36", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_37", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_38", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_39", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_40_47_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_40_47[CAN_DB_BMS_CELL_VOLTAGES_40_47_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_40", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_41", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_42", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_43", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_44", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_45", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_46", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_47", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_48_55_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_48_55[CAN_DB_BMS_CELL_VOLTAGES_48_55_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_48", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_49", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_50", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_51", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_52", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_53", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_54", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_55", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_56_63_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_56_63[CAN_DB_BMS_CELL_VOLTAGES_56_63_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_56", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_57", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_58", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_59", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_60", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_61", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_62", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_63", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_64_71_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_64_71[CAN_DB_BMS_CELL_VOLTAGES_64_71_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_64", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_65", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_66", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_67", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_68", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_69", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_70", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_71", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_72_79_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_72_79[CAN_DB_BMS_CELL_VOLTAGES_72_79_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_72", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_73", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_74", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_75", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_76", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_77", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_78", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_79", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_80_87_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_80_87[CAN_DB_BMS_CELL_VOLTAGES_80_87_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_80", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_81", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_82", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_83", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_84", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_85", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_86", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_87", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_88_95_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_88_95[CAN_DB_BMS_CELL_VOLTAGES_88_95_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_88", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_89", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_90", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_91", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_92", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_93", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_94", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_95", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_96_103_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_96_103[CAN_DB_BMS_CELL_VOLTAGES_96_103_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_96", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_97", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_98", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_99", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_100", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_101", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_102", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_103", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_104_111_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_104_111[CAN_DB_BMS_CELL_VOLTAGES_104_111_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_104", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_105", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_106", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_107", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_108", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_109", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_110", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_111", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_CELL_VOLTAGES_112_119_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_CELL_VOLTAGES_112_119[CAN_DB_BMS_CELL_VOLTAGES_112_119_SIGNAL_COUNT] = {
    {.name = "CELL_VOLTAGE_112", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_113", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_114", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_115", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_116", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_117", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_118", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "CELL_VOLTAGE_119", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_TEMPERATURES_0_7_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_TEMPERATURES_0_7[CAN_DB_BMS_TEMPERATURES_0_7_SIGNAL_COUNT] = {
    {.name = "TEMPERATURE_0", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_1", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_2", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_3", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_4", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_5", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_6", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_7", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_TEMPERATURES_8_15_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_TEMPERATURES_8_15[CAN_DB_BMS_TEMPERATURES_8_15_SIGNAL_COUNT] = {
    {.name = "TEMPERATURE_8", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_9", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_10", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_11", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_12", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_13", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_14", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_15", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_TEMPERATURES_16_31_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_TEMPERATURES_16_31[CAN_DB_BMS_TEMPERATURES_16_31_SIGNAL_COUNT] = {
    {.name = "TEMPERATURE_16", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_17", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_18", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_19", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_20", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_21", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_22", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_23", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_TEMPERATURES_32_39_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_TEMPERATURES_32_39[CAN_DB_BMS_TEMPERATURES_32_39_SIGNAL_COUNT] = {
    {.name = "TEMPERATURE_32", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_33", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_34", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_35", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_36", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_37", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_38", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_39", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_TEMPERATURES_40_47_SIGNAL_COUNT 8
static const CANDatabaseSignal_t can_db_signals_BMS_TEMPERATURES_40_47[CAN_DB_BMS_TEMPERATURES_40_47_SIGNAL_COUNT] = {
    {.name = "TEMPERATURE_40", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_41", .bitpos = 8, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_42", .bitpos = 16, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_43", .bitpos = 24, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_44", .bitpos = 32, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_45", .bitpos = 40, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_46", .bitpos = 48, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_47", .bitpos = 56, .bitmask = 0xFFULL},
};

#define CAN_DB_BMS_TEMPERATURES_48_49_SIGNAL_COUNT 2
static const CANDatabaseSignal_t can_db_signals_BMS_TEMPERATURES_48_49[CAN_DB_BMS_TEMPERATURES_48_49_SIGNAL_COUNT] = {
    {.name = "TEMPERATURE_48", .bitpos = 0, .bitmask = 0xFFULL},
    {.name = "TEMPERATURE_49", .bitpos = 8, .bitmask = 0xFFULL},
};

#define CAN_DB_VCU_EEPROM_COMMAND_SIGNAL_COUNT 3
static const CANDatabaseSignal_t can_db_signals_VCU_EEPROM_COMMAND[CAN_DB_VCU_EEPROM_COMMAND_SIGNAL_COUNT] = {
    {.name = "VCU_EEPROM_COMMAND_INSTRUCTION", .bitpos = 0, .bitmask = 0xFFFFULL},
    {.name = "VCU_EEPROM_COMMAND_ADDRESS", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "VCU_EEPROM_COMMAND_DATA", .bitpos = 32, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_VCU_EEPROM_RESPONSE_SIGNAL_COUNT 3
static const CANDatabaseSignal_t can_db_signals_VCU_EEPROM_RESPONSE[CAN_DB_VCU_EEPROM_RESPONSE_SIGNAL_COUNT] = {
    {.name = "VCU_EEPROM_COMMAND_INSTRUCTION", .bitpos = 0, .bitmask = 0xFFFFULL},
    {.name = "VCU_EEPROM_COMMAND_ADDRESS", .bitpos = 16, .bitmask = 0xFFFFULL},
    {.name = "VCU_EEPROM_COMMAND_DATA", .bitpos = 32, .bitmask = 0xFFFFFFFFULL},
};

#define CAN_DB_MESSAGE_COUNT 37
static const CANDatabaseMessage_t can_db_messages[CAN_DB_MESSAGE_COUNT] = {
    {.name = "VCU_STATUS", .can_id = 256, .num_signals = CAN_DB_VCU_STATUS_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_VCU_STATUS},
    {.name = "VCU_SENSOR_INPUT", .can_id = 1536, .num_signals = CAN_DB_VCU_SENSOR_INPUT_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_VCU_SENSOR_INPUT},
    {.name = "VCU_DEBUG_MESSAGE", .can_id = 1617, .num_signals = CAN_DB_VCU_DEBUG_MESSAGE_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_VCU_DEBUG_MESSAGE},
    {.name = "AMK_RL_ERRORS_1", .can_id = 1284, .num_signals = CAN_DB_AMK_RL_ERRORS_1_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_AMK_RL_ERRORS_1},
    {.name = "AMK_RL_ERRORS_2", .can_id = 1288, .num_signals = CAN_DB_AMK_RL_ERRORS_2_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_AMK_RL_ERRORS_2},
    {.name = "AMK_RL_MOTOR_REQUEST", .can_id = 512, .num_signals = CAN_DB_AMK_RL_MOTOR_REQUEST_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_AMK_RL_MOTOR_REQUEST},
    {.name = "AMK_RL_MOTOR_FEEDBACK", .can_id = 516, .num_signals = CAN_DB_AMK_RL_MOTOR_FEEDBACK_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_AMK_RL_MOTOR_FEEDBACK},
    {.name = "AMK_RL_POWER_CONSUMPTION", .can_id = 520, .num_signals = CAN_DB_AMK_RL_POWER_CONSUMPTION_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_AMK_RL_POWER_CONSUMPTION},
    {.name = "AMK_RL_TEMPERATURES", .can_id = 1280, .num_signals = CAN_DB_AMK_RL_TEMPERATURES_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_AMK_RL_TEMPERATURES},
    {.name = "ECUMASTER_GPS_POSITION", .can_id = 1024, .num_signals = CAN_DB_ECUMASTER_GPS_POSITION_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_ECUMASTER_GPS_POSITION},
    {.name = "ECUMASTER_GPS_VELOCITY", .can_id = 1025, .num_signals = CAN_DB_ECUMASTER_GPS_VELOCITY_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_ECUMASTER_GPS_VELOCITY},
    {.name = "ECUMASTER_GPS_HEADING_IMU0", .can_id = 1026, .num_signals = CAN_DB_ECUMASTER_GPS_HEADING_IMU0_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_ECUMASTER_GPS_HEADING_IMU0},
    {.name = "ECUMASTER_GPS_IMU1", .can_id = 1027, .num_signals = CAN_DB_ECUMASTER_GPS_IMU1_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_ECUMASTER_GPS_IMU1},
    {.name = "ECUMASTER_GPS_UTC", .can_id = 1028, .num_signals = CAN_DB_ECUMASTER_GPS_UTC_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_ECUMASTER_GPS_UTC},
    {.name = "BMS_CELL_VOLTAGES_0_7", .can_id = 1792, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_0_7_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_0_7},
    {.name = "BMS_CELL_VOLTAGES_8_15", .can_id = 1793, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_8_15_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_8_15},
    {.name = "BMS_CELL_VOLTAGES_16_23", .can_id = 1794, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_16_23_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_16_23},
    {.name = "BMS_CELL_VOLTAGES_24_31", .can_id = 1795, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_24_31_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_24_31},
    {.name = "BMS_CELL_VOLTAGES_32_39", .can_id = 1796, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_32_39_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_32_39},
    {.name = "BMS_CELL_VOLTAGES_40_47", .can_id = 1797, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_40_47_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_40_47},
    {.name = "BMS_CELL_VOLTAGES_48_55", .can_id = 1798, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_48_55_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_48_55},
    {.name = "BMS_CELL_VOLTAGES_56_63", .can_id = 1799, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_56_63_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_56_63},
    {.name = "BMS_CELL_VOLTAGES_64_71", .can_id = 1800, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_64_71_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_64_71},
    {.name = "BMS_CELL_VOLTAGES_72_79", .can_id = 1801, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_72_79_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_72_79},
    {.name = "BMS_CELL_VOLTAGES_80_87", .can_id = 1802, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_80_87_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_80_87},
    {.name = "BMS_CELL_VOLTAGES_88_95", .can_id = 1803, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_88_95_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_88_95},
    {.name = "BMS_CELL_VOLTAGES_96_103", .can_id = 1804, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_96_103_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_96_103},
    {.name = "BMS_CELL_VOLTAGES_104_111", .can_id = 1805, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_104_111_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_104_111},
    {.name = "BMS_CELL_VOLTAGES_112_119", .can_id = 1806, .num_signals = CAN_DB_BMS_CELL_VOLTAGES_112_119_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_CELL_VOLTAGES_112_119},
    {.name = "BMS_TEMPERATURES_0_7", .can_id = 1808, .num_signals = CAN_DB_BMS_TEMPERATURES_0_7_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_TEMPERATURES_0_7},
    {.name = "BMS_TEMPERATURES_8_15", .can_id = 1809, .num_signals = CAN_DB_BMS_TEMPERATURES_8_15_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_TEMPERATURES_8_15},
    {.name = "BMS_TEMPERATURES_16_31", .can_id = 1810, .num_signals = CAN_DB_BMS_TEMPERATURES_16_31_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_TEMPERATURES_16_31},
    {.name = "BMS_TEMPERATURES_32_39", .can_id = 1811, .num_signals = CAN_DB_BMS_TEMPERATURES_32_39_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_TEMPERATURES_32_39},
    {.name = "BMS_TEMPERATURES_40_47", .can_id = 1812, .num_signals = CAN_DB_BMS_TEMPERATURES_40_47_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_TEMPERATURES_40_47},
    {.name = "BMS_TEMPERATURES_48_49", .can_id = 1813, .num_signals = CAN_DB_BMS_TEMPERATURES_48_49_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_BMS_TEMPERATURES_48_49},
    {.name = "VCU_EEPROM_COMMAND", .can_id = 1872, .num_signals = CAN_DB_VCU_EEPROM_COMMAND_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_VCU_EEPROM_COMMAND},
    {.name = "VCU_EEPROM_RESPONSE", .can_id = 1873, .num_signals = CAN_DB_VCU_EEPROM_RESPONSE_SIGNAL_COUNT, .signals = (CANDatabaseSignal_t*)can_db_signals_VCU_EEPROM_RESPONSE},
};

#endif /* INC_CAN_MESSAGES_H_ */
